#!/bin/bash
./update_build $@ || exit

if [ "$1" == "-d"]; then
	DEBUG_OPTS=-#d:t:F
fi

. ./mysqld_vars

trap 'killall mysqld; exit' 2 3 9 15

mysqld --datadir=$MYVAR --basedir=$SHARE --lc-messages-dir=$SHARE --socket=$SOCKET --pid=$PIDFILE $DEBUG_OPTS 2>&1 | tee mysqld.log | grep ptnk &
sleep 3
mysql -u root -S $SOCKET
killall mysqld
