#!/bin/bash

. ./mysqld_vars

rm -rf $MYVAR/*
{ echo "create database mysql;"; echo "use mysql;"; cat $SRCDIR/scripts/mysql_system_tables.sql $SRCDIR/scripts/mysql_system_tables_data.sql; } | mysqld --datadir=$MYVAR --basedir=$SHARE --lc-messages-dir=$SHARE --socket=$SOCKET --pid=$PIDFILE --bootstrap
