#!/bin/bash
./update_build $@ || exit
. ./mysqld_vars

trap 'killall mysqld; exit' 2 3 9 15

mysqld --datadir=$MYVAR --basedir=$SHARE --lc-messages-dir=$SHARE --socket=$SOCKET --pid=$PIDFILE $DEBUG_OPTS &> mysqld.log &
sleep 3

rspec t/myptnk_spec.rb

killall mysqld
