#!/bin/bash
if [ "$1" == "-d" ]; then
	sudo rm /usr/local/mysql
	sudo ln -s /usr/local/mysql-dbg /usr/local/mysql
	WAF_OPTS=--debug
	VARIANT=dbg
else
	sudo rm /usr/local/mysql
	sudo ln -s /usr/local/mysql-rel /usr/local/mysql
	VARIANT=rel
fi

(cd ..; ./waf build_$VARIANT) || exit
../waf $WAF_OPTS configure clean build install || exit
